---
deployment:
  tasks:
    - /bin/bash -lc 'set -e
        DEPLOYPATH=/home/cecnsros/public_html/responsables-app;
        mkdir -p "$DEPLOYPATH";
        /usr/bin/rsync -az --delete
          --exclude ".git"
          --exclude ".gitignore"
          --exclude ".cpanel.yml"
          --exclude "database/"
          ./ "$DEPLOYPATH"/'
