---
deployment:
  tasks:
    - /bin/bash -lc 'set -euxo pipefail;
        DEPLOYPATH=/home/cecnsros/public_html/responsables-app;
        mkdir -p "$DEPLOYPATH";
        # empaqueta desde el repo y extrae en el destino (sin rsync/ssh)
        tar --exclude=.git --exclude=.gitignore --exclude=.cpanel.yml --exclude=database -cf - . \
        | tar -xf - -C "$DEPLOYPATH"'
