---
deployment:
  tasks:
    - /bin/bash -lc 'set -e
        shopt -s dotglob;
        SRC=/home/cecnsros/repositories/responsables-app;
        DST=/home/cecnsros/public_html/responsables-app;
        /bin/mkdir -p "$DST";
        /bin/rm -rf "$DST"/*;
        /bin/cp -a "$SRC"/* "$DST"/;
        /bin/rm -rf "$DST/.git"'
